name: Richiesta traduzione
description: Richiedi la traduzione di un libretto che ti piacerebbe utilizzare
title: "[Traduzione]: "
labels:
  - richiesta traduzione
  - libretto
body:
  - type: markdown
    attributes:
      value: Grazie per aver dedicato del tempo per compilare questa richiesta! ❤️
  - type: input
    id: contatto
    attributes:
      label: Contact Details
      description: Come possiamo metterci in contatto con te se abbiamo bisogno di
        ulteriori informazioni?
      placeholder: es. email@example.com
    validations:
      required: false
  - type: input
    id: libretto
    attributes:
      label: Libretto
      description: Come si chiama il libretto di cui desideri la traduzione?
    validations:
      required: true
  - type: textarea
    id: risorsa
    attributes:
      label: Dove possiamo recuperare la risorsa da tradurre?
      placeholder: Inserisci qui link, istruzioni, allegati, ecc.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Codice di condotta
      description: Inviando questa segnalazione, accetti di rispettare il nostro
        [codice di condotta](../CODE_OF_CONDUCT.md)
      options:
        - label: Accetto di seguire il codice di condotta di questo progetto
          required: true
