name: Update class list

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run Node.js script
        run: node scripts/update-class-list-readme.js

      - name: Commit changes
        run: |
          git add .
          git commit -m "docs(README): Update class list [skip ci]"
          git push origin master
